### ISSUE TITLE
Unable to build project in vs2022

### ISSUE THREAD

**Issue by munibhassan** [pgvoorhees/MicroSIP#2]
I just clone repo and it me to upgrade it to newer version vs2022(143) but after doing that I am unable to build that project :(, Any solution for that ?

**Comment by pgvee** [comment]
Best thing to do is not to clone from me, but the the upstream: https://www.microsip.org/source

**Comment by pgvee** [comment]
This was a private build of an old version that just had a modification or two I needed.

**Comment by pgvee** [comment]
This was a private build of an old version that just had a modification or two I needed.
